name: Proyecto Maven Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  modulo3_P2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Mostrar versi贸n de Java y Maven
        run: |
          echo "Versi贸n de Java:"
          java -version
          echo "Versi贸n de Maven:"
          mvn -version

      - name: Compilar el proyecto con Maven
        run: mvn -f hola-mundo/pom.xml clean install

      - name: Mostrar ubicaci贸n del .jar generado
        run: |
          JAR_PATH=$(find target -name "*.jar" | grep -v "original" | head -n 1)
          echo "Archivo .jar generado: $JAR_PATH"

      - name: Ejecutar .jar generado (si tiene clase Main)
        run: |
          JAR_PATH=$(find target -name "*.jar" | grep -v "original" | head -n 1)
          java -jar "$JAR_PATH"
